name: efosm
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
    sdk: ">=3.1.0 <4.0.0"

dependencies:
    dartz: ^0.10.1
    device_info_plus: ^9.1.1
    dio: ^5.4.0
    flutter:
        sdk: flutter
    flutter_bloc: ^8.1.3
    flutter_hooks: ^0.20.4
    flutter_localizations:
        sdk: flutter
    flutter_multi_formatter: ^2.12.4
    flutter_riverpod: ^2.4.9
    # flutter_screenutil: ^5.9.0
    flutter_svg: ^2.0.9
    freezed_annotation: ^2.4.1
    geocoding: ^2.1.1
    get_it: ^7.6.6
    go_router: ^13.0.1
    google_fonts: ^6.1.0
    heroicons: ^0.9.0
    hive: ^2.2.3
    hive_flutter: ^1.1.0
    hooks_riverpod: ^2.4.9
    image: ^4.1.4
    image_picker: ^1.0.7
    infinite_scroll_pagination: ^4.0.0
    intl: ^0.18.1
    json_annotation: ^4.8.1
    location: ^5.0.0
    lottie: ^2.7.0
    riverpod_annotation: ^2.3.3
    smooth_page_indicator: ^1.1.0
    timeline_tile: ^2.0.0

dev_dependencies:
    build_runner: ^2.4.8
    flutter_test:
        sdk: flutter
    freezed: ^2.4.6
    json_serializable: ^6.7.1
    mocktail: ^1.0.2
    riverpod_generator: ^2.3.3
    riverpod_lint: ^2.3.7
    very_good_analysis: ^5.1.0

flutter:
    uses-material-design: true
    generate: true
    assets:
        - assets/lottie/
        - assets/svg/
        # - assets/image/
    fonts:
        - family: Poppins
          fonts:
              - asset: assets/fonts/Poppins-Bold.ttf
                weight: 700
              - asset: assets/fonts/Poppins-SemiBold.ttf
                weight: 600
              - asset: assets/fonts/Poppins-Medium.ttf
                weight: 500
              - asset: assets/fonts/Poppins-Regular.ttf
                weight: 400
              - asset: assets/fonts/Poppins-Thin.ttf
                weight: 300
              - asset: assets/fonts/Poppins-Italic.ttf
                weight: 400
                style: italic
